sonar.projectKey=boardgames
sonar.organization=ceemeese
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.exclusions=\
backend/db/**,\
package.json,\
package-lock.json,\
backend/src/test/**,\
backend/src/utils/**,\
backend/src/middleware/**,\
backend/src/app.js,\
frontend/src/app.js,\
frontend/**
