# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_ACCESS: ${{ secrets.SECRET_ACCESS }}
      BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
        
    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Start database test
      run: docker compose -f docker-compose.dev.yaml up -d
      working-directory: ./backend

    - name: Wait for db
      run: sleep 3
      working-directory: ./backend

    - name: Run unit test
      run: npm run unit-test
      working-directory: ./backend

    - name: Run integration test
      run: npm run integration-test
      working-directory: ./backend
