name: Sonarqube
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        
      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run Docker DB
        run: npm run database:test
        working-directory: ./backend

      - name: Esperar a que la DB esté lista
        run: sleep 10

      - name: Run unit test
        run: npm run unit-test
        working-directory: ./backend

      - name: Run integration test
        run: npm run integration-test
        working-directory: ./backend

      - name: Check coverage files
        run: ls -l ./backend/coverage
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}